---
- name: Install dependencies
  hosts: localhost
  tags: depend
  become: yes
  tasks:
    - name: yum install dependencies
      ansible.builtin.yum:
        name:
          - debootstrap
          - grub2-efi-x64-modules
      when: ansible_facts['distribution'] == 'Fedora'

- name: Download and create build folders 
  hosts: localhost
  gather_facts: false
  tags: extract
  vars_files:
    - ./build_vars.yaml
    
  tasks:
  - name: Create build folders
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ build_folder }}"
      - "{{ download_folder }}/memtest86"
      - "{{ download_folder }}/isolinux"
      - "{{ build_folder }}/{{ distro_short_name }}{{ distro_version }}"

  - name: Ensure shell scripts are executable
    file:
      dest: "{{ item }}"
      mode: 'a+x'
    loop:
      - src/mount.sh
      - src/install_preq.sh
  
  - name: Bootstrap ubuntu
    become: yes
    ansible.builtin.command:
      cmd: debootstrap --arch={{ architecture }} --variant=minbase jammy {{ chroot_folder }} {{ ubuntu_mirror }}
      creates: "{{ build_folder }}/chroot"

  - name: Copy scripts from src folder to chroot env
    tags: debug
    become: yes
    ansible.posix.synchronize:
      src: ./src
      dest: "{{ chroot_folder }}"
      checksum: yes

  - name: "Copy build_vars"
    tags: debug
    become: yes
    ansible.builtin.copy:
      src: "build_vars.yaml"
      dest: "{{ chroot_folder }}/src/build_vars.yaml"
      remote_src: yes

  - name: Download and extract memtest86+
    ansible.builtin.unarchive:
      src: https://www.memtest86.com/downloads/memtest86-usb.zip
      dest: "{{ download_folder }}/memtest86/"
      remote_src: yes

- name: Configs
  hosts: localhost
  gather_facts: false
  become: yes
  tags: config
  vars_files:
    - ./build_vars.yaml
  tasks:
  - name: Create chroot folders
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ chroot_folder }}/build/log"

  - name: Set hostname
    ansible.builtin.copy:
      dest: "{{ chroot_folder }}/etc/hostname"
      content: "{{ hostname }}"

  - name: Set sources.list
    ansible.builtin.copy:
      dest: "{{ chroot_folder }}/etc/apt/sources.list"
      content: |
        deb {{ ubuntu_mirror }} {{ubuntu_version}} main restricted universe multiverse
        deb-src {{ ubuntu_mirror }} {{ubuntu_version}} main restricted universe multiverse

        deb {{ ubuntu_mirror }} {{ubuntu_version}}-security main restricted universe multiverse
        deb-src {{ ubuntu_mirror }} {{ubuntu_version}}-security main restricted universe multiverse

        deb {{ ubuntu_mirror }} {{ubuntu_version}}-updates main restricted universe multiverse
        deb-src {{ ubuntu_mirror }} {{ubuntu_version}}-updates main restricted universe multiverse
    
- name: Prepare chroot
  hosts: localhost
  tags: chroot
  become: yes
  vars_files:
    - ./build_vars.yaml
  tasks:
  - name: mount chroot environment and run shell
    block:
      - name: Mount /run
        tags: debug
        ansible.builtin.command: 
          cmd: mount -o bind /run/ {{ chroot_folder }}/run
          creates: "{{ chroot_folder }}/run/udev"

      - name: Mount /dev
        tags: debug
        ansible.builtin.command: 
          cmd: mount --bind /dev/ {{ chroot_folder }}/dev
          creates: "{{ chroot_folder }}/dev/cpu"

      - name: "Chroot: Mount dirs" # TODO: Mount from ansible instead
        tags: debug
        ansible.builtin.shell: chroot {{ chroot_folder }} /src/mount.sh

      - name: "Chroot: Run Main script"
        ansible.builtin.shell: chroot {{ chroot_folder }} /src/install_preq.sh

    always:
      - name: Umount /proc
        retries: 3
        delay: 3
        tags: unmount
        ansible.builtin.command: 
          cmd: umount {{ chroot_folder }}/proc -l
          removes: "{{ chroot_folder }}/proc/cpuinfo"

      - name: Umount /sys
        retries: 3
        delay: 3
        tags: unmount
        ansible.builtin.command: 
          cmd: umount {{ chroot_folder }}/sys
          removes: "{{ chroot_folder }}/sys/bus/"

      - name: Umount /run
        retries: 3
        delay: 3
        tags: unmount
        ansible.builtin.command: 
          cmd: umount {{ chroot_folder }}/run
          removes: "{{ chroot_folder }}/run/user"

      - name: Umount /dev/pts
        retries: 3
        delay: 3
        tags: unmount
        ignore_errors: true
        ansible.builtin.command: 
          cmd: umount {{ chroot_folder }}/dev/pts -l
          removes: "{{ chroot_folder }}/dev/pts/ptmx"
      
      - name: Umount /dev
        retries: 3
        delay: 3
        tags: unmount
        ansible.builtin.command: 
          cmd: umount {{ chroot_folder }}/dev -l
          removes: "{{ chroot_folder }}/dev/cpu"

- name: Assemble ISO
  hosts: localhost
  tags: iso
  become: yes
  vars_files:
    - ./build_vars.yaml
  tasks:
    - name: Create iso folders
      ansible.builtin.file:
        path: "{{ iso_folder }}/{{ item }}"
        state: directory
      loop: 
        - casper
        - isolinux
        - install
        - boot/grub
        - boot/EFI
      
    - name: Copy linux kernel
      ansible.builtin.command:
        cmd: "cp {{ chroot_folder }}/boot/vmlinuz {{ iso_folder }}/casper/vmlinuz"
    
    - name: Give read permissions on kernel
      become: yes
      ansible.builtin.command:
        cmd: "chmod +r {{ iso_folder }}/casper/vmlinuz"
      
    - name: Copy initrd
      ansible.builtin.command:
        cmd: "cp {{ chroot_folder }}/src/initrd {{ iso_folder }}/casper/initrd"     
    
    - name: Copy memtest86+ binary
      ansible.builtin.copy:
        src: "{{ download_folder }}/memtest86/memtest86-usb.img"
        dest: "{{ iso_folder }}/install/memtest86"

    - name: Copy manifest
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ iso_folder }}/casper/"
      loop:
        - "{{ chroot_folder }}/src/filesystem.manifest"
        - "{{ chroot_folder }}/src/filesystem.manifest-desktop"

    - name: Remove previous squashfs if exists
      ansible.builtin.file:
        dest: "{{ iso_folder }}/casper/filesystem.squashfs"
        state: absent

    - name: Compress filesystem
      ansible.builtin.command:
        cmd: mksquashfs {{ chroot_folder }} {{ iso_folder }}/casper/filesystem.squashfs

    - name: Generate filesize
      ansible.builtin.shell:
        cmd: printf $(du -sx --block-size=1 {{ chroot_folder }} | cut -f1) > {{ iso_folder }}/casper/filesystem.size

    - name: copy grub config
      ansible.builtin.template:
        src: src/iso_grub.cfg.j2
        dest: "{{ iso_folder }}/boot/grub/grub.cfg"

    # - name: Generate UEFI Image
    #   ansible.builtin.command:
    #     cmd: grub-mkstandalone --format=x86_64-efi --output=/boot/EFI/bootx64.efi --locales="" --fonts="" boot/grub/grub.cfg=isolinux/grub.cfg
    #     chdir: "{{ iso_folder }}"
        
    - name: Create diskdefines file
      ansible.builtin.copy:
        dest: "{{ iso_folder }}/README.diskdefines"
        content: |
          #define DISKNAME  BigBother
          #define TYPE  binary
          #define TYPEbinary  1
          #define ARCH  amd64
          #define ARCHamd64  1
          #define DISKNUM  1
          #define DISKNUM1  1
          #define TOTALNUM  0
          #define TOTALNUM0  1

- name: Package ISO
  hosts: localhost
  tags: package
  vars_files:
    - ./build_vars.yaml
  tasks:
    - name: Generate iso
      ansible.builtin.shell:
        cmd: grub-mkrescue -o {{ iso_output }} {{ iso_folder }}

    - name: Get checksum of iso
      tags: test1
      ansible.builtin.stat:
        path: "{{ iso_output }}" 
        checksum_algorithm: sha256
        get_checksum: yes
      register: sha256

    - name: Get checksum of iso
      ansible.builtin.stat:
        path: "{{ iso_output }}" 
        checksum_algorithm: sha512
        get_checksum: yes
      register: sha512

    - name: insert to checksum file
      ansible.builtin.copy:
        dest: "{{ build_folder }}/{{ distro_short_name }}{{ distro_version }}/check.sum"
        content: |
          sha256_{{ sha256.stat.checksum }}
          sha512_{{ sha512.stat.checksum }}

    - name: add README
      ansible.builtin.copy:
        dest: "{{ build_folder }}/{{ distro_short_name }}{{ distro_version }}/README.md"
        src: README.md
        remote_src: true
    
    - name: pack to tar
      ansible.builtin.command:
        cmd: "tar -cf {{ distro_short_name }}{{ distro_version }}.tar BigBother.iso README.md check.sum"
        chdir: "{{ build_folder }}/{{ distro_short_name }}{{ distro_version }}"

    - name: ensure torrent not already existing
      ansible.builtin.file:
        path: "{{ build_folder }}/{{ distro_short_name }}{{ distro_version }}/{{ distro_short_name }}{{ distro_version }}.tar.torrent"
        state: absent

    - name: Create torrent file
      tags: test1
      ansible.builtin.command:
        cmd: "mktorrent -a {{ torrent_trackers | join(' -a ')}} {{ distro_short_name }}{{ distro_version }}.tar" 
        chdir: "{{ build_folder }}/{{ distro_short_name }}{{ distro_version }}"